# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build App in local"
  lane :build_local do
    make_build_folder
    build_ios_app(
      scheme: "HLNimbleiOSChallenge_Debug", 
      workspace: "HLNimbleiOSChallenge.xcworkspace",
      configuration: "Debug", 
      export_method: "development",
      output_directory: "./build",
      output_name: "HLNimbleiOSChallenge_Dev.ipa",
      silent: true,
      clean: true
    )
  end

  desc "Build App in Staging"
  lane :build_staging do
    make_build_folder
    build_ios_app(
      scheme: "HLNimbleiOSChallenge_Staging", 
      workspace: "HLNimbleiOSChallenge.xcworkspace",
      configuration: "Staging", 
      export_method: "ad-hoc",
      output_directory: "./build",
      output_name: "HLNimbleiOSChallenge_Staging.ipa",
      silent: true,
      clean: true
    )
  end

  desc "Build App in Store"
  lane :build_release do
    make_build_folder
    build_ios_app(
      scheme: "HLNimbleiOSChallenge_Release", 
      workspace: "HLNimbleiOSChallenge.xcworkspace",
      configuration: "Release", 
      export_method: "app-store",
      output_directory: "./build",
      output_name: "HLNimbleiOSChallenge.ipa",
      silent: true,
      clean: true
    )
  end

  desc "Make build Folder"
  private_lane :make_build_folder do
    sh "mkdir -p ./build"
  end
end
